// 폴래 cute — 3가지 1020 타겟 컬러 테마

const CUTE_THEMES = {
  jellyPeach: {
    name: '젤리피치',
    tagline: '둥글둥글 친구 톤',
    // Page
    bg: '#FFF5F0',
    bgGrad: 'radial-gradient(ellipse at top, #FFE0E8 0%, transparent 50%), radial-gradient(ellipse at bottom right, #F0E0FF 0%, transparent 50%), #FFF5F0',
    surface: '#FFFFFF',
    surfaceAlt: '#FFF8F3',
    border: '#FFE5DC',
    divider: '#FFEEE5',
    // Brand
    primary: '#FF7AA8',   // hot pink
    primaryDeep: '#E0588B',
    primarySoft: '#FFE0EC',
    accent: '#FFB088',    // peach (secondary)
    accentSoft: '#FFE8DC',
    pop: '#C8A8E9',       // lavender pop
    popSoft: '#F0E5FF',
    // Vote colors
    yes: '#FF7AA8',
    yesSoft: '#FFE0EC',
    maybe: '#FFA962',
    maybeSoft: '#FFE5D0',
    no: '#9580C0',
    noSoft: '#EBE5F5',
    // Text
    ink: '#2A1A24',
    inkSoft: '#5C4954',
    inkMute: '#9A8590',
    inkFaint: '#C7B5BE',
    // Characters
    charBg: '#FFE8EE',
    blush: '#FF85A1',
    charPalette: ['#FFC8DE','#FFB088','#FFD9A8','#C8A8E9','#A8D8FF','#FFAACC','#FFCDB8','#D9C5F0'],
  },
  mintCampus: {
    name: '민트캠퍼스',
    tagline: '대학 동아리 신선 톤',
    bg: '#F4FBF9',
    bgGrad: 'radial-gradient(ellipse at top, #D8F2EA 0%, transparent 55%), radial-gradient(ellipse at bottom left, #FFF5D0 0%, transparent 50%), #F4FBF9',
    surface: '#FFFFFF',
    surfaceAlt: '#F8FCFA',
    border: '#D8EEE6',
    divider: '#E8F5F0',
    primary: '#3CC9A8',
    primaryDeep: '#1FA888',
    primarySoft: '#D8F5EC',
    accent: '#FFD93D',
    accentSoft: '#FFF6D8',
    pop: '#FF8A80',
    popSoft: '#FFE5E2',
    yes: '#3CC9A8',
    yesSoft: '#D8F5EC',
    maybe: '#FFAA3D',
    maybeSoft: '#FFEBCC',
    no: '#FF6B6B',
    noSoft: '#FFE0E0',
    ink: '#1A2E2A',
    inkSoft: '#3D5550',
    inkMute: '#7A8E88',
    inkFaint: '#B5C5C0',
    charBg: '#E8F8F2',
    blush: '#FF9580',
    charPalette: ['#A8E8D5','#FFD980','#FFB0A8','#A8DDFF','#C8E5A8','#FFC8D5','#B8E8C8','#FFD0A0'],
  },
  y2kPop: {
    name: 'Y2K POP',
    tagline: '인스타 스토리 톤',
    bg: '#F5F0FF',
    bgGrad: 'radial-gradient(ellipse at 20% 10%, #E5D8FF 0%, transparent 50%), radial-gradient(ellipse at 80% 90%, #D8FFE5 0%, transparent 50%), radial-gradient(ellipse at 80% 20%, #FFE0F0 0%, transparent 40%), #F5F0FF',
    surface: '#FFFFFF',
    surfaceAlt: '#FAF5FF',
    border: '#E5DCFF',
    divider: '#EEE5FF',
    primary: '#9B5DE5',
    primaryDeep: '#7A3DC2',
    primarySoft: '#EBDDFF',
    accent: '#00E89A',
    accentSoft: '#D5FFE8',
    pop: '#F15BB5',
    popSoft: '#FFD8EE',
    yes: '#00C896',
    yesSoft: '#D0FFE8',
    maybe: '#FFB800',
    maybeSoft: '#FFF0CC',
    no: '#F15BB5',
    noSoft: '#FFD8EE',
    ink: '#1F0F2E',
    inkSoft: '#4A3560',
    inkMute: '#8870A0',
    inkFaint: '#C0B0D0',
    charBg: '#F0E8FF',
    blush: '#F15BB5',
    charPalette: ['#C8B0FF','#FFB0DC','#A8FFD5','#FFE085','#FF9FB8','#B0E5FF','#E8B0FF','#FFCC85'],
  },
};

window.CUTE_THEMES = CUTE_THEMES;
